name: Auto merge
on: 
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, edited]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          intervalSeconds: 1
          timeoutSeconds: 60
